name: Build DAL with Yotta

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  schedule:
    # Runs every day at 9 am
    - cron: '0 9 * * *'

jobs:
  build-yotta:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-10.15, windows-2016]
      fail-fast: false
    name: Yotta ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.5
        uses: actions/setup-python@v2
        with:
          python-version: '3.5'
      - name: Install GCC ARM, CMake, and Ninja (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-16.04' }}
        run: |
          sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
          sudo add-apt-repository -y ppa:adrozdoff/cmake
          sudo apt-get update -qq
          sudo apt-get install -y gcc-arm-embedded
          sudo apt-get install -y cmake
          sudo apt-get install -y ninja-build
      - name: Install GCC ARM, CMake, and Ninja (Windows)
        if: ${{ matrix.os == 'windows-2016' }}
        run: |
          choco install gcc-arm-embedded
          choco install cmake
          choco install ninja
      - name: Install GCC ARM, CMake, and Ninja (macOS)
        if: ${{ matrix.os == 'macos-10.15' }}
        run: |
          brew tap ArmMbed/homebrew-formulae
          brew install arm-none-eabi-gcc
          brew install cmake
          brew install ninja
      - name: Install Yotta
        run: python -m pip install yotta
      - name: Check Versions
        run: |
          arm-none-eabi-gcc --version
          cmake --version
          ninja --version
          python --version
          python -m pip --version
          yotta --version
      - name: Set Yotta target
        run: yt target bbc-microbit-classic-gcc
      - name: Build with Yotta
        run: yotta --verbose build
      - name: Upload hex file
        uses: actions/upload-artifact@v1
        with:
          name: hex-yotta-${{ matrix.os }}
          path: build/bbc-microbit-classic-gcc/source/microbit-samples-combined.hex
